allowed_ssh_cidr      = "189.62.45.78/32"
private_key_path      = "~/.ssh/besu-key"
public_key_path       = "~/.ssh/besu-key.pub"
instance_type_node1   = "c6i.2xlarge"
instance_type_besu    = "c6i.xlarge"
instance_type_caliper = "m6i.4xlarge"
project_name          = "besu-distributed"
